#! /bin/bash

V1='only_camera_model_v1'
V2='only_camera_model_v2'
c_d4='c_d4_model_v1'

if [ $# != 1 ] ; then
    echo "please argument [run [1 ~ 9]]"
    exit 1
elif [ $1 == '1' ] ; then
    python3 main.py $v2 '346' # チャレンジモデル
elif [ $1 == '2' ] ; then
    python3 main.py $v2 '344' # チャレンジモデル
elif [ $1 == '3' ] ; then
    python3 main.py $v2 '345' # ?
elif [ $1 == '4' ] ; then
    python3 main.py $v2 '348' # ?
elif [ $1 == '5' ] ; then
    python3 main.py $v2 '350' # 安定?
elif [ $1 == '6' ] ; then
    python3 main.py $v2 '352'  # normalモデル
elif [ $1 == '7' ] ; then
    python3 main.py $v2 '353' # 安定モデル
elif [ $1 == '8' ] ; then
    python3 main.py $c_d4 '353' # 安定し、ノイズに強いモデル
elif [ $1 == '9' ] ; then
    python3 main.py $c_d4 '355' # 安定し、ノイズにvery強いモデル
else
    echo "please argument [1 ~ 9]"
    exit 1
fi
