#! /bin/bash

if [ $# != 1 ] ; then
    echo "please argument [run.sh {model} {base_speed}]"
    exit 1
elif [ $1 == '1' ] ; then
    python3 main.py 'only_camera_model_v2' '346' # チャレンジモデル
elif [ $1 == '2' ] ; then
    python3 main.py 'only_camera_model_v2' '350' # normalモデル
elif [ $1 == '3' ] ; then
    python3 main.py 'only_camera_model_v2' '353' # 安定しモデル
elif [ $1 == '4' ] ; then
    python3 main.py 'c_d4_model_v1' '353' # 安定し、ノイズに強いモデル
elif [ $1 == '5' ] ; then
    python3 main.py 'c_d4_model_v1' '355' # 安定し、ノイズにvery強いモデル
else
    echo "please argument [1 ~ 5]"
    exit 1
fi
